### ISSUE TITLE
Failed when deploy dev box infrastructure due to missing implicit dependency

### ISSUE THREAD

**Issue by duongthaiha** [Azure-Samples/Devcenter#5]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy dev box using the instruction in the Read Me file
RG=devcenter
DEPLOYINGUSERID=$(az ad signed-in-user show --query id -o tsv)
az group create -n $RG -l eastus
DCNAME=$(az deployment group create -g $RG -f bicep/common.bicep -p nameseed=devbox devboxProjectUser=$DEPLOYINGUSERID --query 'properties.outputs.devcenterName.value' -o tsv)
az deployment group create -g $RG -f bicep/devbox.bicep -p devcenterName=$DCNAME
The error show at the last command

### Any log messages given by the failure
>
The deployment show error as below 
 "code": "ParentResourceNotFound",
      "message": "Can not perform requested operation on nested resource. Parent resource 'developers/developers-win11plain-eastus' not found."

However rerun the same command fix the error
az deployment group create -g $RG -f bicep/devbox.bicep -p devcenterName=$DCNAME

### Expected/desired behavior
> az deployment group create -g $RG -f bicep/devbox.bicep -p devcenterName=$DCNAME
will run correctly first time 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
I think this might be because the schedule stop using the string manupilation so the implicit dependency is not created.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Gordonby** [comment]
Closed by #6
